// portal/src/app/features/pdf-viewer/components/form-field-overlay.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy, ViewChild, ElementRef, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subject, takeUntil } from 'rxjs';
import { FormField } from '../../../core/models/form-field.model';

export interface FieldMoveEvent {
  x: number;
  y: number;
  isValidPosition?: boolean;
}

export interface FieldResizeEvent {
  width: number;
  height: number;
}

@Component({
  selector: 'app-form-field-overlay',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './form-field-overlay.component.html',
  styleUrls: ['./form-field-overlay.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FormFieldOverlayComponent implements OnInit, OnDestroy {
  @Input() field!: FormField;
  @Input() scale: number = 1.0;
  @Input() isSelected: boolean = false;
  @Input() allFields: FormField[] = [];
  @Input() snapToGrid: boolean = false;
  @Input() gridSize: number = 10;

  @Output() fieldClick = new EventEmitter<FormField>();
  @Output() fieldMove = new EventEmitter<FieldMoveEvent>();
  @Output() fieldResize = new EventEmitter<FieldResizeEvent>();
  @Output() fieldDelete = new EventEmitter<void>();

  @ViewChild('overlayRef', { static: false }) overlayRef!: ElementRef;

  private destroy$ = new Subject<void>();

  // Local state
  isDragging = false;
  isResizing = false;
  isOverlapping = false;
  dragStart = { x: 0, y: 0 };
  resizeStart = { x: 0, y: 0, width: 0, height: 0 };
  dragPreview = { x: 0, y: 0 };

  ngOnInit(): void {}

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  onMouseDown(event: MouseEvent): void {
    event.preventDefault();
    event.stopPropagation();
    
    const rect = this.overlayRef?.nativeElement.getBoundingClientRect();
    if (!rect) return;

    const isResizeHandle = event.target === event.currentTarget.querySelector('.resize-handle');
    
    if (isResizeHandle) {
      this.isResizing = true;
      this.resizeStart = {
        x: event.clientX,
        y: event.clientY,
        width: this.field.width,
        height: this.field.height
      };
    } else {
      this.isDragging = true;
      this.dragStart = {
        x: event.clientX - rect.left,
        y: event.clientY - rect.top
      };
    }

    // Add global event listeners
    document.addEventListener('mousemove', this.handleMouseMove.bind(this));
    document.addEventListener('mouseup', this.handleMouseUp.bind(this));
  }

  onClick(): void {
    this.fieldClick.emit(this.field);
  }

  onDelete(): void {
    this.fieldDelete.emit();
  }

  private handleMouseMove(event: MouseEvent): void {
    if (this.isDragging) {
      let newX = (event.clientX - this.dragStart.x) / this.scale;
      let newY = (event.clientY - this.dragStart.y) / this.scale;
      
      // Apply snap to grid if enabled
      const snappedPosition = this.snapToGridPosition(newX, newY);
      newX = snappedPosition.x;
      newY = snappedPosition.y;
      
      // Update drag preview for visual feedback
      this.dragPreview = { x: newX, y: newY };
      
      // Check for overlap
      const wouldOverlap = this.checkForOverlap(newX, newY, this.field.width, this.field.height);
      this.isOverlapping = wouldOverlap;
      
      // Move the field with overlap information
      this.fieldMove.emit({
        x: newX,
        y: newY,
        isValidPosition: !wouldOverlap
      });
    } else if (this.isResizing) {
      const deltaX = (event.clientX - this.resizeStart.x) / this.scale;
      const deltaY = (event.clientY - this.resizeStart.y) / this.scale;
      const newWidth = Math.max(50, this.resizeStart.width + deltaX);
      const newHeight = Math.max(20, this.resizeStart.height + deltaY);
      
      this.fieldResize.emit({
        width: newWidth,
        height: newHeight
      });
    }
  }

  private handleMouseUp(): void {
    this.isDragging = false;
    this.isResizing = false;
    this.isOverlapping = false;

    // Remove global event listeners
    document.removeEventListener('mousemove', this.handleMouseMove.bind(this));
    document.removeEventListener('mouseup', this.handleMouseUp.bind(this));
  }

  // Function to check if a position would cause overlap with other fields
  private checkForOverlap(x: number, y: number, width: number, height: number): boolean {
    const currentField = {
      x, y, width, height, pageNumber: this.field.pageNumber
    };
    
    return this.allFields.some(otherField => {
      if (otherField.id === this.field.id || otherField.pageNumber !== this.field.pageNumber) {
        return false;
      }
      
      return !(
        currentField.x >= otherField.x + otherField.width ||
        currentField.x + currentField.width <= otherField.x ||
        currentField.y >= otherField.y + otherField.height ||
        currentField.y + currentField.height <= otherField.y
      );
    });
  }

  // Function to snap position to grid
  private snapToGridPosition(x: number, y: number): { x: number, y: number } {
    if (!this.snapToGrid) return { x, y };
    
    return {
      x: Math.round(x / this.gridSize) * this.gridSize,
      y: Math.round(y / this.gridSize) * this.gridSize
    };
  }

  // Determine border color based on state
  getBorderColor(): string {
    if (this.isOverlapping) return '#dc3545'; // Red for overlap
    if (this.isSelected) return '#007bff'; // Blue for selected
    return '#ddd'; // Default gray
  }

  // Determine background color based on state
  getBackgroundColor(): string {
    if (this.isOverlapping) return 'rgba(220, 53, 69, 0.1)'; // Red tint for overlap
    if (this.isSelected) return 'rgba(0, 123, 255, 0.1)'; // Blue tint for selected
    return 'rgba(255, 255, 255, 0.8)'; // Default white
  }

  // Get overlay styles
  getOverlayStyles(): { [key: string]: any } {
    return {
      left: this.field.x * this.scale + 'px',
      top: this.field.y * this.scale + 'px',
      width: this.field.width * this.scale + 'px',
      height: this.field.height * this.scale + 'px',
      fontSize: this.field.fontSize * this.scale + 'px',
      color: this.field.color,
      border: `2px solid ${this.getBorderColor()}`,
      backgroundColor: this.getBackgroundColor(),
      cursor: this.isDragging ? 'grabbing' : 'grab',
      transition: this.isDragging ? 'none' : 'all 0.2s ease',
      boxShadow: this.isOverlapping ? '0 0 10px rgba(220, 53, 69, 0.5)' : 
                 this.isSelected ? '0 0 5px rgba(0, 123, 255, 0.3)' : 'none',
      zIndex: this.isDragging ? 1000 : (this.isSelected ? 100 : 10),
    };
  }

  // Get label styles
  getLabelStyles(): { [key: string]: any } {
    return {
      color: this.isOverlapping ? '#dc3545' : this.field.color,
      textShadow: this.isOverlapping ? '1px 1px 2px rgba(255,255,255,0.8)' : 'none'
    };
  }
}

<div
  #overlayRef
  class="form-field-overlay"
  [class.selected]="isSelected"
  [class.overlapping]="isOverlapping"
  [class.dragging]="isDragging"
  [ngStyle]="getOverlayStyles()"
  (click)="onClick()"
  (mousedown)="onMouseDown($event)">
  
  <span [ngStyle]="getLabelStyles()">
    {{ field.label }}
    <span *ngIf="isOverlapping" class="warning-icon">⚠️</span>
  </span>
  
  <div *ngIf="isSelected" class="field-controls">
    <div class="resize-handle" 
         title="Resize field">
    </div>
    
    <button class="delete-handle" 
            (click)="onDelete()"
            title="Delete field">
      ×
    </button>
  </div>
</div>

// src/components/FormFieldOverlay.tsx
import React, { useState, useRef, useCallback } from 'react';
import { FormField } from '../types/FormField';

interface FormFieldOverlayProps {
  field: FormField;
  scale: number;
  isSelected: boolean;
  onClick: () => void;
  onMove: (newX: number, newY: number, isValidPosition?: boolean) => void;
  onResize: (newWidth: number, newHeight: number) => void;
  onDelete: () => void;
  allFields?: FormField[]; // Add all fields to check for overlaps
  snapToGrid?: boolean;
  gridSize?: number;
}

const FormFieldOverlay: React.FC<FormFieldOverlayProps> = ({
  field,
  scale,
  isSelected,
  onClick,
  onMove,
  onResize,
  onDelete,
  allFields = [],
  snapToGrid = false,
  gridSize = 10
}) => {
  const [isDragging, setIsDragging] = useState(false);
  const [isResizing, setIsResizing] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });
  const [resizeStart, setResizeStart] = useState({ x: 0, y: 0, width: 0, height: 0 });
  const [isOverlapping, setIsOverlapping] = useState(false);
  const [dragPreview, setDragPreview] = useState({ x: 0, y: 0 });
  const overlayRef = useRef<HTMLDivElement>(null);

  // Function to check if a position would cause overlap with other fields
  const checkForOverlap = useCallback((x: number, y: number, width: number, height: number): boolean => {
    const currentField = {
      x, y, width, height, pageNumber: field.pageNumber
    };
    
    return allFields.some(otherField => {
      if (otherField.id === field.id || otherField.pageNumber !== field.pageNumber) {
        return false;
      }
      
      return !(
        currentField.x >= otherField.x + otherField.width ||
        currentField.x + currentField.width <= otherField.x ||
        currentField.y >= otherField.y + otherField.height ||
        currentField.y + currentField.height <= otherField.y
      );
    });
  }, [field.id, field.pageNumber, allFields]);

  // Function to snap position to grid
  const snapToGridPosition = useCallback((x: number, y: number): { x: number, y: number } => {
    if (!snapToGrid) return { x, y };
    
    return {
      x: Math.round(x / gridSize) * gridSize,
      y: Math.round(y / gridSize) * gridSize
    };
  }, [snapToGrid, gridSize]);

  const handleMouseDown = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    
    const rect = overlayRef.current?.getBoundingClientRect();
    if (!rect) return;

    const isResizeHandle = e.target === e.currentTarget.querySelector('.resize-handle');
    
    if (isResizeHandle) {
      setIsResizing(true);
      setResizeStart({
        x: e.clientX,
        y: e.clientY,
        width: field.width,
        height: field.height
      });
    } else {
      setIsDragging(true);
      setDragStart({
        x: e.clientX - rect.left,
        y: e.clientY - rect.top
      });
    }
  };

  const handleMouseMove = (e: MouseEvent) => {
    if (isDragging) {
      let newX = (e.clientX - dragStart.x) / scale;
      let newY = (e.clientY - dragStart.y) / scale;
      
      // Apply snap to grid if enabled
      const snappedPosition = snapToGridPosition(newX, newY);
      newX = snappedPosition.x;
      newY = snappedPosition.y;
      
      // Update drag preview for visual feedback
      setDragPreview({ x: newX, y: newY });
      
      // Check for overlap
      const wouldOverlap = checkForOverlap(newX, newY, field.width, field.height);
      setIsOverlapping(wouldOverlap);
      
      // Move the field with overlap information
      onMove(newX, newY, !wouldOverlap);
    } else if (isResizing) {
      const deltaX = (e.clientX - resizeStart.x) / scale;
      const deltaY = (e.clientY - resizeStart.y) / scale;
      const newWidth = Math.max(50, resizeStart.width + deltaX);
      const newHeight = Math.max(20, resizeStart.height + deltaY);
      onResize(newWidth, newHeight);
    }
  };

  const handleMouseUp = () => {
    setIsDragging(false);
    setIsResizing(false);
    setIsOverlapping(false);
  };

  React.useEffect(() => {
    if (isDragging || isResizing) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
      return () => {
        document.removeEventListener('mousemove', handleMouseMove);
        document.removeEventListener('mouseup', handleMouseUp);
      };
    }
  }, [isDragging, isResizing, dragStart, resizeStart, scale, handleMouseMove]);

  // Determine border color based on state
  const getBorderColor = () => {
    if (isOverlapping) return '#dc3545'; // Red for overlap
    if (isSelected) return '#007bff'; // Blue for selected
    return '#ddd'; // Default gray
  };

  // Determine background color based on state
  const getBackgroundColor = () => {
    if (isOverlapping) return 'rgba(220, 53, 69, 0.1)'; // Red tint for overlap
    if (isSelected) return 'rgba(0, 123, 255, 0.1)'; // Blue tint for selected
    return 'rgba(255, 255, 255, 0.8)'; // Default white
  };

  return (
    <div
      ref={overlayRef}
      className={`form-field-overlay ${isSelected ? 'selected' : ''} ${isOverlapping ? 'overlapping' : ''}`}
      style={{
        left: field.x * scale,
        top: field.y * scale,
        width: field.width * scale,
        height: field.height * scale,
        fontSize: field.fontSize * scale,
        color: field.color,
        border: `2px solid ${getBorderColor()}`,
        backgroundColor: getBackgroundColor(),
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        cursor: isDragging ? 'grabbing' : 'grab',
        userSelect: 'none',
        transition: isDragging ? 'none' : 'all 0.2s ease',
        boxShadow: isOverlapping ? '0 0 10px rgba(220, 53, 69, 0.5)' : 
                   isSelected ? '0 0 5px rgba(0, 123, 255, 0.3)' : 'none',
        zIndex: isDragging ? 1000 : (isSelected ? 100 : 10),
      }}
      onClick={onClick}
      onMouseDown={handleMouseDown}
    >
      <span style={{ 
        fontSize: '12px', 
        fontWeight: 'bold',
        color: isOverlapping ? '#dc3545' : field.color,
        textShadow: isOverlapping ? '1px 1px 2px rgba(255,255,255,0.8)' : 'none'
      }}>
        {field.label}
        {isOverlapping && <span style={{ fontSize: '10px', marginLeft: '4px' }}>⚠️</span>}
      </span>
      {isSelected && (
        <>
          <div 
            className="resize-handle"
            style={{
              position: 'absolute',
              bottom: -5,
              right: -5,
              width: 10,
              height: 10,
              backgroundColor: '#007bff',
              border: '2px solid white',
              borderRadius: '50%',
              cursor: 'nw-resize'
            }}
          />
          <button
            className="delete-handle"
            onClick={(e) => {
              e.stopPropagation();
              onDelete();
            }}
            style={{
              position: 'absolute',
              top: -5,
              right: -5,
              width: 20,
              height: 20,
              backgroundColor: '#dc3545',
              border: '2px solid white',
              borderRadius: '50%',
              cursor: 'pointer',
              color: 'white',
              fontSize: '12px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontWeight: 'bold'
            }}
          >
            ×
          </button>
        </>
      )}
    </div>
  );
};

export default FormFieldOverlay;
