// portal/src/app/features/pdf-filler/components/pdf-filler.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject, takeUntil, combineLatest } from 'rxjs';
import { StateService } from '../../../core/services/state.service';
import { PdfService } from '../../../core/services/pdf.service';
import { ConfigService } from '../../../core/services/config.service';
import { FormField, PDFFormData } from '../../../core/models/form-field.model';

@Component({
  selector: 'app-pdf-filler',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './pdf-filler.component.html',
  styleUrls: ['./pdf-filler.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class PdfFillerComponent implements OnInit, OnDestroy {
  private destroy$ = new Subject<void>();

  // State observables
  formFields$ = this.stateService.formFields$;
  formData$ = this.stateService.formData$;
  isLoading$ = this.stateService.isLoading$;
  flattenForm$ = this.stateService.flattenForm$;
  pdfFile$ = this.stateService.pdfFile$;

  // Local state
  flattenForm = true;

  constructor(
    private stateService: StateService,
    private pdfService: PdfService,
    private configService: ConfigService
  ) {}

  ngOnInit(): void {
    // Subscribe to flatten form state
    this.flattenForm$.pipe(
      takeUntil(this.destroy$)
    ).subscribe(flatten => {
      this.flattenForm = flatten;
    });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  handleFieldChange(fieldName: string, value: string | number): void {
    this.stateService.updateFormData(fieldName, value);
  }

  loadSampleData(): void {
    this.formFields$.pipe(
      takeUntil(this.destroy$)
    ).subscribe(formFields => {
      const sampleData = this.configService.createSampleFormData(formFields);
      this.stateService.setFormData(sampleData);
    });
  }

  async generateFilledPDF(): Promise<void> {
    combineLatest([
      this.pdfFile$,
      this.formFields$
    ]).pipe(
      takeUntil(this.destroy$)
    ).subscribe(async ([pdfFile, formFields]) => {
      if (!pdfFile || formFields.length === 0) {
        alert('Please load a PDF and add form fields first');
        return;
      }

      this.stateService.setIsLoading(true);
      try {
        // First generate PDF with form fields
        const pdfWithForm = await this.pdfService.generatePDFWithForm(pdfFile, formFields);
        
        const formData = this.stateService.getCurrentFormData();
        
        let filledPdf: Uint8Array;
        
        if (this.flattenForm) {
          // Fill the form with data and flatten (remove borders)
          filledPdf = await this.pdfService.fillAndFlattenPDFForm(
            new File([new Uint8Array(pdfWithForm)], 'form.pdf', { type: 'application/pdf' }),
            formData,
            formFields // Pass formFields to get page information
          );
        } else {
          // Fill the form with data but keep borders
          filledPdf = await this.pdfService.fillPDFForm(
            new File([new Uint8Array(pdfWithForm)], 'form.pdf', { type: 'application/pdf' }),
            formData
          );
        }
        
        this.pdfService.downloadPDF(filledPdf, 'filled-form.pdf');
      } catch (error) {
        console.error('Error generating filled PDF:', error);
        alert('Error generating PDF. Please check the console for details.');
      } finally {
        this.stateService.setIsLoading(false);
      }
    });
  }

  async downloadFormPDF(): Promise<void> {
    combineLatest([
      this.pdfFile$,
      this.formFields$
    ]).pipe(
      takeUntil(this.destroy$)
    ).subscribe(async ([pdfFile, formFields]) => {
      if (!pdfFile || formFields.length === 0) {
        alert('Please load a PDF and add form fields first');
        return;
      }

      this.stateService.setIsLoading(true);
      try {
        const pdfWithForm = await this.pdfService.generatePDFWithForm(pdfFile, formFields);
        this.pdfService.downloadPDF(pdfWithForm, 'form-template.pdf');
      } catch (error) {
        console.error('Error generating form PDF:', error);
        alert('Error generating PDF. Please check the console for details.');
      } finally {
        this.stateService.setIsLoading(false);
      }
    });
  }

  onFlattenFormChange(checked: boolean): void {
    this.stateService.setFlattenForm(checked);
  }

  // Utility method for template
  trackByFieldId(index: number, field: FormField): string {
    return field.id;
  }

  // Get form data for template
  getFormDataValue(fieldName: string): string {
    const formData = this.stateService.getCurrentFormData();
    return formData[fieldName]?.toString() || '';
  }
}

<div class="config-section" *ngIf="formFields$ | async as formFields">
  <h3>Fill PDF Form</h3>
  
  <div class="form-group">
    <button class="button" (click)="loadSampleData()">
      Load Sample Data
    </button>
  </div>

  <div class="form-group">
    <label class="flatten-option">
      <input
        type="checkbox"
        [checked]="flattenForm"
        (change)="onFlattenFormChange($event.target.checked)">
      <span class="option-text">
        <strong>Flatten form fields</strong> - Remove borders and keep only text content
        <br>
        <small class="option-hint">
          <span *ngIf="flattenForm">✓ PDF will contain only text without form field borders</span>
          <span *ngIf="!flattenForm">⚠ PDF will keep form field borders</span>
        </small>
      </span>
    </label>
  </div>

  <div *ngIf="formFields.length > 0; else noFields" class="form-fields">
    <div *ngFor="let field of formFields; trackBy: trackByFieldId" class="form-group">
      <label>
        {{ field.label }} 
        <span *ngIf="field.required" class="required">*</span>
      </label>
      <input
        [type]="field.type === 'number' ? 'number' : field.type === 'date' ? 'date' : 'text'"
        [value]="getFormDataValue(field.name)"
        (input)="handleFieldChange(field.name, $event.target.value)"
        [placeholder]="field.placeholder"
        [required]="field.required"
        class="form-input">
    </div>
  </div>

  <ng-template #noFields>
    <p class="no-fields-message">Add form fields to the PDF to enable form filling.</p>
  </ng-template>

  <div class="form-group">
    <button 
      class="button success"
      (click)="generateFilledPDF()"
      [disabled]="isLoading$ | async">
      <span *ngIf="isLoading$ | async">Generating...</span>
      <span *ngIf="!(isLoading$ | async)">
        {{ flattenForm ? 'Generate Filled PDF (No Borders)' : 'Generate Filled PDF (With Borders)' }}
      </span>
    </button>
  </div>

  <div *ngIf="(formData$ | async) as formData" class="form-data-preview">
    <h4>Form Data Preview:</h4>
    <pre class="preview-content">{{ formData | json }}</pre>
  </div>
</div>

<div class="config-section" *ngIf="!(formFields$ | async)?.length">
  <h3>Fill PDF Form</h3>
  <p>Add form fields to the PDF to enable form filling.</p>
</div>

// src/components/PDFFiller.tsx
import React, { useState } from 'react';
import { FormField, PDFFormData } from '../types/FormField';
import { AdvancedPDFService } from '../services/AdvancedPDFService';
import { PDFService } from '../services/PDFService';

interface PDFFillerProps {
  pdfFile: File | null;
  formFields: FormField[];
  onPDFGenerated: (pdfBytes: Uint8Array) => void;
}

const PDFFiller: React.FC<PDFFillerProps> = ({
  pdfFile,
  formFields,
  onPDFGenerated
}) => {
  const [formData, setFormData] = useState<PDFFormData>({});
  const [isLoading, setIsLoading] = useState(false);
  const [flattenForm, setFlattenForm] = useState(true); // Default to flatten (no borders)

  const handleFieldChange = (fieldName: string, value: string | number) => {
    setFormData(prev => ({
      ...prev,
      [fieldName]: value
    }));
  };

  const loadSampleData = () => {
    const sampleData = AdvancedPDFService.createSampleFormData(formFields);
    setFormData(sampleData);
  };

  const generateFilledPDF = async () => {
    if (!pdfFile || formFields.length === 0) {
      alert('Please load a PDF and add form fields first');
      return;
    }

    setIsLoading(true);
    try {
      // First generate PDF with form fields
      const pdfWithForm = await AdvancedPDFService.generatePDFWithForm(pdfFile, formFields);
      
      let filledPdf: Uint8Array;
      
      if (flattenForm) {
        // Fill the form with data and flatten (remove borders)
        filledPdf = await AdvancedPDFService.fillAndFlattenPDFForm(
          new File([new Uint8Array(pdfWithForm)], 'form.pdf', { type: 'application/pdf' }),
          formData,
          formFields // Pass formFields to get page information
        );
      } else {
        // Fill the form with data but keep borders
        filledPdf = await AdvancedPDFService.fillPDFForm(
          new File([new Uint8Array(pdfWithForm)], 'form.pdf', { type: 'application/pdf' }),
          formData
        );
      }
      
      onPDFGenerated(filledPdf);
      AdvancedPDFService.downloadPDF(filledPdf, 'filled-form.pdf');
    } catch (error) {
      console.error('Error generating filled PDF:', error);
      alert('Error generating PDF. Please check the console for details.');
    } finally {
      setIsLoading(false);
    }
  };

  const downloadFormPDF = async () => {
    if (!pdfFile || formFields.length === 0) {
      alert('Please load a PDF and add form fields first');
      return;
    }

    setIsLoading(true);
    try {
      const pdfWithForm = await PDFService.generatePDFWithForm(pdfFile, formFields);
      onPDFGenerated(pdfWithForm);
      PDFService.downloadPDF(pdfWithForm, 'form-template.pdf');
    } catch (error) {
      console.error('Error generating form PDF:', error);
      alert('Error generating PDF. Please check the console for details.');
    } finally {
      setIsLoading(false);
    }
  };

  if (formFields.length === 0) {
    return (
      <div className="config-section">
        <h3>Fill PDF Form</h3>
        <p>Add form fields to the PDF to enable form filling.</p>
      </div>
    );
  }

  return (
    <div className="config-section">
      <h3>Fill PDF Form</h3>
      
      <div className="form-group">
        <button 
          className="button"
          onClick={loadSampleData}
        >
          Load Sample Data
        </button>
        
        {1 < 0 && <button 
          className="button success"
          onClick={downloadFormPDF}
          disabled={isLoading}
        >
          Download Form Template
        </button>}
      </div>

      <div className="form-group">
        <label style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '15px' }}>
          <input
            type="checkbox"
            checked={flattenForm}
            onChange={(e) => setFlattenForm(e.target.checked)}
            style={{ marginRight: '5px' }}
          />
          <span>
            <strong>Flatten form fields</strong> - Remove borders and keep only text content
            <br />
            <small style={{ color: '#666' }}>
              {flattenForm ? '✓ PDF will contain only text without form field borders' : '⚠ PDF will keep form field borders'}
            </small>
          </span>
        </label>
      </div>

      {formFields.map(field => (
        <div key={field.id} className="form-group">
          <label>
            {field.label} {field.required && <span style={{color: 'red'}}>*</span>}
          </label>
          <input
            type={field.type === 'number' ? 'number' : field.type === 'date' ? 'date' : 'text'}
            value={formData[field.name] || ''}
            onChange={(e) => handleFieldChange(field.name, e.target.value)}
            placeholder={field.placeholder}
            required={field.required}
            style={{ width: '100%' }}
          />
        </div>
      ))}

      <div className="form-group">
        <button 
          className="button success"
          onClick={generateFilledPDF}
          disabled={isLoading}
        >
          {isLoading ? 'Generating...' : 
           flattenForm ? 'Generate Filled PDF (No Borders)' : 'Generate Filled PDF (With Borders)'}
        </button>
      </div>

      {Object.keys(formData).length > 0 && (
        <div className="form-group">
          <h4>Form Data Preview:</h4>
          <pre style={{ 
            background: '#f5f5f5', 
            padding: '10px', 
            borderRadius: '4px',
            fontSize: '12px',
            maxHeight: '200px',
            overflow: 'auto'
          }}>
            {JSON.stringify(formData, null, 2)}
          </pre>
        </div>
      )}
    </div>
  );
};

export default PDFFiller;
